language: php

php:
  - hhvm
  - 5.5
  - 7.0
  - 7.2

before_script:
  - composer install --dev

script:
  - ./vendor/bin/phpunit --bootstrap vendor/autoload.php test/serhatozdal/optional/OptionalTests.php